{
 "title": "Uptime",
 "description": "Ketersediaan server, database, dan komponen PLG Stack dalam rentang waktu dashboard.",
 "tags": [ "plg-stack" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": "label_values(up{job=\"node\"}, env)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(up{job=\"node\", env=~\"$env\"}, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ketersediaan rata-rata",
   "type": "stat",
   "description": "Persentase menit saat server mengirim data, dihitung sejak data pertamanya dalam rentang waktu ini. Oranye di bawah 99.9%, merah di bawah 99%.",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 * clamp_max(sum_over_time((max by (host, env) (present_over_time(up{job=\"node\", env=~\"$env\", host=~\"$host\"}[1m])))[$__range:1m]) / (scalar(floor(vector(time() / 60))) - ceil(clamp_min(min by (host, env) (min_over_time(timestamp(up{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m])), time() - $__range_s + 0.001) / 60) + 1), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server dipantau",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(100 * clamp_max(sum_over_time((max by (host, env) (present_over_time(up{job=\"node\", env=~\"$env\", host=~\"$host\"}[1m])))[$__range:1m]) / (scalar(floor(vector(time() / 60))) - ceil(clamp_min(min by (host, env) (min_over_time(timestamp(up{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m])), time() - $__range_s + 0.001) / 60) + 1), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total waktu tidak melapor",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(60 * clamp_min((scalar(floor(vector(time() / 60))) - ceil(clamp_min(min by (host, env) (min_over_time(timestamp(up{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m])), time() - $__range_s + 0.001) / 60) + 1) - sum_over_time((max by (host, env) (present_over_time(up{job=\"node\", env=~\"$env\", host=~\"$host\"}[1m])))[$__range:1m]), 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reboot",
   "type": "stat",
   "description": "Jumlah reboot dalam rentang waktu, terlihat dari uptime server yang kembali ke nol.",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (host, env) (resets((node_time_seconds{job=\"node\", env=~\"$env\", host=~\"$host\"} - node_boot_time_seconds{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m]))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ketersediaan per server",
   "type": "table",
   "description": "Menit tanpa data dari server. Putus jaringan singkat tidak terhitung karena agent mengirim ulang datanya setelah tersambung; yang tersisa berarti server atau agent mati. Diurutkan dari yang terburuk.",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "100 * clamp_max(sum_over_time((max by (host, env) (present_over_time(up{job=\"node\", env=~\"$env\", host=~\"$host\"}[1m])))[$__range:1m]) / (scalar(floor(vector(time() / 60))) - ceil(clamp_min(min by (host, env) (min_over_time(timestamp(up{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m])), time() - $__range_s + 0.001) / 60) + 1), 1)",
     "legendFormat": "__auto"
    },
    {
     "expr": "60 * clamp_min((scalar(floor(vector(time() / 60))) - ceil(clamp_min(min by (host, env) (min_over_time(timestamp(up{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m])), time() - $__range_s + 0.001) / 60) + 1) - sum_over_time((max by (host, env) (present_over_time(up{job=\"node\", env=~\"$env\", host=~\"$host\"}[1m])))[$__range:1m]), 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host, env) (resets((node_time_seconds{job=\"node\", env=~\"$env\", host=~\"$host\"} - node_boot_time_seconds{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (host, env) (node_time_seconds{job=\"node\", env=~\"$env\", host=~\"$host\"} - node_boot_time_seconds{job=\"node\", env=~\"$env\", host=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max by (host, env) (timestamp(up{job=\"node\", env=~\"$env\", host=~\"$host\"}) or max_over_time(timestamp(up{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status melapor",
   "type": "state-timeline",
   "description": "Merah berarti ada menit tanpa data dari server dalam periode bar itu. Persempit rentang waktu untuk melihat menit persisnya.",
   "gridPos": { "x": 0, "y": 13, "w": 24, "h": 9 },
   "targets": [
    {
     "expr": "min_over_time((max by (host) (present_over_time(up{job=\"node\", env=~\"$env\", host=~\"$host\"}[1m])) or 0 * (min by (host) (min_over_time(timestamp(up{job=\"node\", env=~\"$env\", host=~\"$host\"})[$__range:1m] @ end())) <= time()))[$__interval:1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Database dan komponen stack", "type": "row", "gridPos": { "x": 0, "y": 22, "w": 24, "h": 1 } },
  {
   "title": "Ketersediaan database",
   "type": "table",
   "description": "Persentase waktu database bisa diakses agent, selama servernya melapor.",
   "gridPos": { "x": 0, "y": 23, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 * avg_over_time((min by (host, env, job) ({__name__=~\"pg_up|mysql_up|redis_up|mongodb_up\", env=~\"$env\", host=~\"$host\"}))[$__range:1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ketersediaan komponen PLG Stack",
   "type": "stat",
   "description": "Diukur Prometheus tiap 30 detik; periode saat Prometheus sendiri mati tidak tercatat.",
   "gridPos": { "x": 12, "y": 23, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=~\"plg-.*\"}[$__range])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}