#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -t 1 ]]; then
	BOLD=$'\e[1m' DIM=$'\e[2m' BLUE=$'\e[34m' RESET=$'\e[0m'
else
	BOLD="" DIM="" BLUE="" RESET=""
fi

info() { printf '\n%s\n' "${BLUE}==>${RESET} ${BOLD}$*${RESET}"; }
die() {
	printf 'ERROR: %s\n' "$*" >&2
	exit 1
}

ask() {
	local var="$1" prompt="$2" default="${3:-}" answer
	if [[ -n "$default" ]]; then
		read -r -p "  $prompt ${DIM}[$default]${RESET}: " answer
	else
		read -r -p "  $prompt: " answer
	fi
	answer="${answer:-$default}"
	[[ "$answer" != *"'"* ]] || die "Nilai tidak boleh mengandung tanda kutip tunggal."
	printf -v "$var" '%s' "$answer"
}

random_password() { od -An -N16 -tx1 /dev/urandom | tr -d ' \n'; }

load_existing() {
	local key value
	while IFS='=' read -r key value; do
		[[ "$key" =~ ^[A-Z_][A-Z0-9_]*$ ]] || continue
		value="${value#\'}"
		value="${value%\'}"
		printf -v "OLD_$key" '%s' "$value"
	done <.env
}

old() {
	local name="OLD_$1"
	printf '%s' "${!name:-${2:-}}"
}

[[ -t 0 ]] || die "Script ini interaktif; jalankan langsung dari terminal."

if [[ -f .env ]]; then
	load_existing
	read -r -p "  .env sudah ada. Nilai lama dipakai sebagai default dan file ditimpa. Lanjut? [Y/n]: " answer
	[[ "${answer:-y}" =~ ^[YyJj] ]] || exit 0
fi

info "Mode deploy"
echo "  standalone : server biasa; Caddy memegang port 80/443 dan mengurus sertifikat TLS."
echo "  dokploy    : deploy sebagai Compose di Dokploy; Traefik Dokploy mengurus domain dan TLS."
default_mode=standalone
[[ "$(old GATEWAY_SCHEME)" == http ]] && default_mode=dokploy
while :; do
	ask MODE "Pilih mode (standalone/dokploy)" "$default_mode"
	[[ "$MODE" == standalone || "$MODE" == dokploy ]] && break
done

info "Domain"
echo "  ${DIM}Agent mengirim data ke domain ingest. Saat stack pindah server, cukup ubah DNS-nya.${RESET}"
ask GRAFANA_DOMAIN "Domain Grafana" "$(old GRAFANA_DOMAIN grafana.example.com)"
ask INGEST_DOMAIN "Domain ingest" "$(old INGEST_DOMAIN ingest.example.com)"

info "Kredensial"
ask GRAFANA_ADMIN_USER "User admin Grafana" "$(old GRAFANA_ADMIN_USER admin)"
ask GRAFANA_ADMIN_PASSWORD "Password admin Grafana" "$(old GRAFANA_ADMIN_PASSWORD "$(random_password)")"
ask INGEST_USER "User ingest (dipakai agent)" "$(old INGEST_USER agent)"
ask INGEST_PASSWORD "Password ingest" "$(old INGEST_PASSWORD "$(random_password)")"

info "Retensi data"
ask PROMETHEUS_RETENTION "Retensi metrik (Prometheus)" "$(old PROMETHEUS_RETENTION 15d)"
ask PROMETHEUS_RETENTION_SIZE "Batas ukuran metrik" "$(old PROMETHEUS_RETENTION_SIZE 8GB)"
ask LOKI_RETENTION "Retensi log (Loki)" "$(old LOKI_RETENTION 14d)"

info "Penyimpanan log"
echo "  local : di volume Docker server ini (ikut dipindah lewat backup/restore)."
echo "  s3    : di bucket S3 / S3-compatible (tidak perlu dipindah, disk lokal aman)."
default_storage=local
[[ "$(old LOKI_CONFIG)" == loki-s3.yaml ]] && default_storage=s3
while :; do
	ask STORAGE "Pilih (local/s3)" "$default_storage"
	[[ "$STORAGE" == local || "$STORAGE" == s3 ]] && break
done
LOKI_CONFIG=loki.yaml
LOKI_S3_BUCKET="" LOKI_S3_REGION="" LOKI_S3_ENDPOINT="" LOKI_S3_ACCESS_KEY_ID="" LOKI_S3_SECRET_ACCESS_KEY=""
LOKI_S3_FORCE_PATH_STYLE=false
if [[ "$STORAGE" == s3 ]]; then
	LOKI_CONFIG=loki-s3.yaml
	ask LOKI_S3_BUCKET "Nama bucket" "$(old LOKI_S3_BUCKET)"
	ask LOKI_S3_REGION "Region" "$(old LOKI_S3_REGION ap-southeast-1)"
	echo "  ${DIM}Kosongkan endpoint dan key jika memakai AWS S3 dengan IAM role.${RESET}"
	ask LOKI_S3_ENDPOINT "Endpoint (MinIO/R2/dll.)" "$(old LOKI_S3_ENDPOINT)"
	ask LOKI_S3_ACCESS_KEY_ID "Access key ID" "$(old LOKI_S3_ACCESS_KEY_ID)"
	ask LOKI_S3_SECRET_ACCESS_KEY "Secret access key" "$(old LOKI_S3_SECRET_ACCESS_KEY)"
	if [[ -n "$LOKI_S3_ENDPOINT" ]]; then
		LOKI_S3_FORCE_PATH_STYLE=true
	fi
fi

if [[ "$MODE" == standalone ]]; then
	COMPOSE_FILE=compose.yaml:compose.standalone.yaml
	GATEWAY_SCHEME=https
else
	COMPOSE_FILE=""
	GATEWAY_SCHEME=http
fi

env_lines() {
	local key
	for key in "$@"; do
		printf "%s='%s'\n" "$key" "${!key}"
	done
}

{
	echo "# Generated by scripts/setup.sh; see .env.example for every option."
	[[ -n "$COMPOSE_FILE" ]] && env_lines COMPOSE_FILE
	env_lines GATEWAY_SCHEME GRAFANA_DOMAIN INGEST_DOMAIN \
		GRAFANA_ADMIN_USER GRAFANA_ADMIN_PASSWORD INGEST_USER INGEST_PASSWORD \
		PROMETHEUS_RETENTION PROMETHEUS_RETENTION_SIZE LOKI_RETENTION LOKI_CONFIG
	if [[ "$STORAGE" == s3 ]]; then
		env_lines LOKI_S3_BUCKET LOKI_S3_REGION LOKI_S3_ENDPOINT LOKI_S3_ACCESS_KEY_ID \
			LOKI_S3_SECRET_ACCESS_KEY LOKI_S3_FORCE_PATH_STYLE
	fi
	for key in ALERT_TELEGRAM_BOT_TOKEN ALERT_TELEGRAM_CHAT_ID ALERT_SLACK_WEBHOOK_URL ALERT_EMAIL_ADDRESSES \
		GF_SMTP_ENABLED GF_SMTP_HOST GF_SMTP_USER GF_SMTP_PASSWORD GF_SMTP_FROM_ADDRESS; do
		value="$(old "$key")"
		if [[ -n "$value" ]]; then
			printf "%s='%s'\n" "$key" "$value"
		fi
	done
} >.env.tmp
chmod 600 .env.tmp
mv .env.tmp .env

info "Selesai, .env ditulis"
if [[ "$MODE" == standalone ]]; then
	cat <<EOF
  1. Arahkan DNS A record $GRAFANA_DOMAIN dan $INGEST_DOMAIN ke IP server ini.
  2. Buka port 80 dan 443 (TCP, plus 443/UDP untuk HTTP/3).
  3. Jalankan: docker compose up -d
EOF
else
	cat <<EOF
  Di Dokploy:
  1. Project "Monitoring" → Create Service → Compose (tipe Docker Compose).
  2. Provider GitHub → repo ini, branch main, Compose Path: ./compose.yaml
  3. Tab Environment → tempel seluruh isi .env (lihat: cat .env).
  4. Tab Domains → tambah dua domain, keduanya ke service "gateway" port 80, HTTPS aktif:
       $GRAFANA_DOMAIN
       $INGEST_DOMAIN
  5. Deploy.
EOF
fi
cat <<EOF

  Grafana : https://$GRAFANA_DOMAIN  (user: $GRAFANA_ADMIN_USER)
  Install agent di setiap server yang dipantau:
    curl -fsSL https://$INGEST_DOMAIN/agent/install.sh | sudo bash
  Saat diminta, isi URL https://$INGEST_DOMAIN, user $INGEST_USER, dan INGEST_PASSWORD dari .env.
EOF
