#!/usr/bin/env python3
"""Generates the PLG Stack dashboards and alert rules from config.toml.

    python3 grafana/generator/generate.py            write the files
    python3 grafana/generator/generate.py --check    fail if they are out of date

Needs Python 3.11+ and nothing else.
"""
import argparse
import json
import sys
from pathlib import Path

import alerts
import dashboards
from builders import to_yaml
from settings import HERE, Settings

ROOT = HERE.parent.parent
DASHBOARD_DIR = Path("grafana/dashboards/PLG Stack")
RULES_FILE = Path("grafana/provisioning/alerting/rules.yaml")
RULES_HEADER = """\
# Generated by grafana/generator/generate.py from grafana/generator/config.toml;
# edit those and regenerate instead of editing this file.
"""


def render(S):
    files = {}
    for uid, dash in dashboards.build(S).items():
        files[DASHBOARD_DIR / f"{uid}.json"] = json.dumps(dash, indent=2, ensure_ascii=False) + "\n"
    rules = to_yaml(alerts.build(S))
    # Grafana expands $VAR in provisioning files, so a literal $ would vanish.
    if "$" in rules:
        raise ValueError("alert rules must not contain '$'; use .Labels / .Values in templates")
    files[RULES_FILE] = RULES_HEADER + rules
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="only report files that are out of date")
    parser.add_argument("--language", help="override `language` from config.toml")
    parser.add_argument("--config", default=HERE / "config.toml", type=Path)
    parser.add_argument("--out", default=ROOT, type=Path, help="repository root to write into")
    args = parser.parse_args()

    try:
        files = render(Settings.load(args.config, args.language))
    except (KeyError, ValueError) as err:
        sys.exit(f"error: {err.args[0] if err.args else err}")

    stale = []
    for rel, content in files.items():
        path = args.out / rel
        if path.exists() and path.read_text() == content:
            continue
        stale.append(rel)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    # The dashboard folder belongs to the generator; anything else in it
    # would be provisioned but never regenerated.
    foreign = sorted(p.relative_to(args.out) for p in (args.out / DASHBOARD_DIR).glob("*")
                     if p.relative_to(args.out) not in files)

    if args.check:
        for rel in stale:
            print(f"out of date: {rel}", file=sys.stderr)
        for rel in foreign:
            print(f"not generated: {rel} (move custom dashboards to another folder)", file=sys.stderr)
        if stale or foreign:
            sys.exit("run: python3 grafana/generator/generate.py")
        return
    for rel in stale:
        print(f"wrote {rel}")
    for rel in foreign:
        print(f"warning: {rel} is not generated; move custom dashboards to another folder", file=sys.stderr)


if __name__ == "__main__":
    main()
